language: python

python:
  2.7

addons:
  postgresql: "9.5"

services:
  - postgresql
  - redis-server

env:
  global:
    - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR
    - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/scraper
    - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/kmanga

before_install:
  - sudo apt-get -qq update
  - wget http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz
  - tar -xzvf kindlegen_linux_2.6_i386_v2_9.tar.gz
  - mv kindlegen bin

install:
  - pip install -r requirements/test.txt
  - pip install coveralls

before_script:
  - echo "VENV=$HOME/virtualenv/python$TRAVIS_PYTHON_VERSION" > bin/kmanga.conf
  - cp kmanga/kmanga/local_settings.py.travis kmanga/kmanga/local_settings.py
  - psql -c "CREATE DATABASE kmanga;" -U postgres
  - kmanga/manage.py makemigrations
  - cp bin/0002_full_text_search.py kmanga/core/migrations/
  - kmanga/manage.py migrate
  - kmanga/manage.py loaddata bin/initialdata.json

script:
  bin/test.sh -c

after_success:
  coveralls
